# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20180111_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
